version: "3.9"

services:
  # Serviço da API FastAPI
  api:
    build: ./api
    container_name: api-aproveitamento
    restart: always
    volumes:
      - ./api/botafogo.db:/data/botafogo.db  # usa o arquivo local
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/data/botafogo.db
    networks:
      - app-network

  # Serviço Worker para extração de dados
  worker:
    build: ./api
    container_name: worker-aproveitamento
    restart: always
    volumes:
      - ./api/botafogo.db:/data/botafogo.db  # mesmo arquivo
    environment:
      - DB_PATH=/data/botafogo.db
    command: python worker.py
    networks:
      - app-network
    depends_on:
      - api

  # Serviço do Streamlit (Frontend)
  web:
    build: ./front
    container_name: streamlit-aproveitamento
    restart: always
    ports:
      - "8505:8505"
    environment:
      - API_BASE_URL=http://api:8000
    networks:
      - app-network
    depends_on:
      - api

# Rede para comunicação entre containers
networks:
  app-network:
    driver: bridge